app:
  name: short-app
  image: antonlarichev/short-app
  version: v1.4
  components: frontend
  port: 80
  replicas: 1
  limits:
    memory: "128Mi"
    cpu: "500m"

env: test
value:
  requirements:
    limits:
      memory: "128Mi"
      cpu: "128Mi"

users:
  - name: Maksat
    role: admin
  - name: Vasya
    role: manager
