apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}-deployment
  #namespace: my-namespace # для деплоя в нужный namespace
spec:
  replicas: {{ .Values.api.replicas}}
  selector:
    matchLabels:
      components: {{ .Values.api.components }}
  template:
    metadata:
      name: short-app
      labels:
        components: {{ .Values.api.components }}
    spec:
      containers:
        - name: short-app
          image: "{{ .Values.api.image }}:{{ .Values.api.version }}"
          ports:
            - containerPort: {{ .Values.api.port }}
          resources:
            limits: {{ .Values.api.limits | toYaml | nindent 14 }}
          env:
            {{- range .Values.api.envs  }}
            {{- $data := dict "name" $.Values.api.name  "env" . }}
            {{- include "env.template" $data | indent 12 }}
            {{- end }}
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:3000/api
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 1
