apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  #namespace: my-namespace # для деплоя в нужный namespace
spec:
  replicas: {{ .Values.app.replicas}}
  selector:
    matchLabels:
      components: {{ .Values.app.components }}
  template:
    metadata:
      name: short-app
      labels:
        components: {{ .Values.app.components }}
    spec:
      containers:
        - name: short-app
          image: "{{ .Values.app.image }}:{{ .Values.app.version }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          resources:
            limits: {{ .Values.app.limits | toYaml | nindent 14 }}
  
