apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: ZGVtbw== # Используються значения в кодеровке base64
  POSTGRES_USER: ZGVtbw== # Генерация пароля в base64 (echo -n demo | base64)
  POSTGRES_PASSWORD: ZGVtbw==  # Обратная команда (echo ZGVtbw== | base64 -D)
